# Generated by Django 5.1.5 on 2025-04-18 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutentry',
            name='reps_per_set',
        ),
        migrations.RemoveField(
            model_name='workoutentry',
            name='sets',
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField()),
                ('set_number', models.PositiveIntegerField()),
                ('workout_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='project.workoutentry')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
    ]
