# Generated by Django 5.1.5 on 2025-04-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_workoutentry_reps_per_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutentry',
            name='weight',
        ),
        migrations.AddField(
            model_name='set',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
