# Generated by Django 5.1.5 on 2025-02-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_nane',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.TextField(blank=True),
        ),
    ]
